[#183698] Incluir Eventos do GA nos itens associados ao uso do microfone
tecsinapse/chat pull request #30
Opened 2022-12-20 13:27 UTC by liperossell

[#183698] Incluir Eventos do GA nos itens associados ao uso do microfone

2022-12-20 13:27 UTC, gitTecsinapse commented
https://tecsinapse.tpondemand.com/entity/183698

2022-12-20 14:38 UTC, gabrielbutka commented on src/components/Chat/Chat.js
> +  reactWrapper: PropTypes.object,
reactWrapper não fica muito claro o que deve ser passado, sugiro usar duas novas props:

```
connectionKey: PropTypes.string.isRequired,
reactGA: PropTypes.object.isRequired,
```

ou usar reactWrapper como shape:

```
reactWrapper: PropTypes.shape({
  connectionKey: PropTypes.string.isRequired,
  reactGA: PropTypes.object.isRequired
}).isRequired
```

2022-12-20 14:42 UTC, gabrielbutka commented on src/components/Chat/Maximized/InputComposer/InputComposer.js
> +    if (micDenied) {
logo acima ele dá um setMicDanied(false), então aqui nunca será verdadeiro, certo?

2022-12-20 14:44 UTC, gabrielbutka requested changes
@liperossell deixei algumas observações

2022-12-21 14:37 UTC, gabrielbutka approved these changes

2022-12-22 19:54 UTC, merged